services:
  sentence-transformers-server:
    build:
      context: ./server
      # if you are behind a corporate proxy uncomment below to pass these values at container build time
      # args:
      #   - HTTP_PROXY
      #   - HTTPS_PROXY
      #   - NO_PROXY
    container_name: sentence_transformers_server
    environment:
      - MODEL=${MODEL}
      # if you are behind a corporate proxy uncomment below to pass these values during the container execution
      # - HTTP_PROXY
      # - HTTPS_PROXY
      # - NO_PROXY
      # - http_proxy
      # - https_proxy
      # - no_proxy
    ports:
      - ${STS_PORT:-8081}:8081
    volumes:
      - ./server:/code/server
      - ./models:/code/server/models
    command:
      - uvicorn
      - --workers
      - "20"
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8081"
      # - --reload # take away in prod
    restart: unless-stopped
