version: '3.7'

services:

  sentence-transformers-server:
    build:
      context: ./server
      # if you are behind a corporate proxy uncomment below to pass these values at container build time
      # args:
      #   - HTTP_PROXY=http://X.X.X.X:Y
      #   - HTTPS_PROXY=http://X.X.X.X:Y
      #   - http_proxy=http://X.X.X.X:Y
      #   - https_proxy=http://X.X.X.X:Y
    container_name: sentence_transformers_server
    environment:
      - MODEL=${MODEL}
      # if you are behind a corporate proxy uncomment below to pass these values during the container execution
      # - HTTP_PROXY=http://X.X.X.X:Y
      # - HTTPS_PROXY=http://X.X.X.X:Y
      # - http_proxy=http://X.X.X.X:Y
      # - https_proxy=http://X.X.X.X:Y
    ports:
      - ${STS_PORT:-8081}:8081
    volumes:
      - ./server:/code/server
    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8081"
      - --reload # take away in prod
    restart: unless-stopped